{% set name = "unicorn-binance-rest-api" %}
{% set version = "2.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicorn_binance_rest_api-{{ version }}.tar.gz
  sha256: 933bb24463eb6bba5f581eeb6c8346be01f206d8451d1542abf8d92430b95058

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - mypy
  run:
    - python
    - cython
    - certifi >=2025.6.15
    - colorama
    - cryptography >=45.0.4
    - dateparser
    - pyopenssl
    - pysocks
    - regex
    - requests >=2.32.4
    - service_identity
    - ujson

test:
  imports:
    - unicorn_binance_rest_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oliver-zehentleitner/unicorn-binance-rest-api
  summary: An unofficial Python API to use the Binance REST APIs.
  description: |
    An unofficial Python API to use the Binance REST APIs (com+testnet,
    com-margin+testnet, com-isolated_margin+testnet, com-futures+testnet,
    us, tr) in an easy, fast, flexible, robust and fully-featured way.
    Part of the UNICORN Binance Suite.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/oliver-zehentleitner/unicorn-binance-rest-api
  doc_url: https://oliver-zehentleitner.github.io/unicorn-binance-rest-api

extra:
  recipe-maintainers:
    - oliver-zehentleitner
