{% set name = "unicorn-binance-rest-api" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-binance-rest-api-{{ version }}.tar.gz
  sha256: 2a42b4d8e08d9354a09470702cbc534896d5a7b5d3aedbd783df8ff117e596bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - certifi
    - colorama
    - cryptography
    - dateparser
    - pyopenssl
    - python >=3.6
    - regex <=2022.3.2
    - requests
    - service_identity
    - ujson
  run:
    - certifi
    - colorama
    - cryptography
    - dateparser
    - pyopenssl
    - python >=3.6
    - regex <=2022.3.2
    - requests
    - service_identity
    - ujson

test:
  imports:
    - unicorn_binance_rest_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-rest-api.html
  summary: An unofficial Python API to use the Binance REST API`s.
  description: |
    An unofficial Python API to use the Binance REST API`s (com+testnet, com-margin+testnet, com-isolated_margin+testnet, 
    com-futures+testnet, us, tr) in a easy, fast, flexible, robust and fully-featured way.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api
  doc_url: https://unicorn-binance-rest-api.docs.lucit.tech/

extra:
  recipe-maintainers:
    - oliver-zehentleitner
