{% set name = "unicorn-binance-rest-api" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-binance-rest-api-{{ version }}.tar.gz
  sha256: 8719ed65dbc9ac13bff801a2a247fa2e83c8e178498a538dce299e0b0d099572

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("cxx") }}
    - certifi
    - colorama
    - cryptography
    - dateparser
    - pyopenssl
    - PySocks
    - regex
    - requests
    - requests  # [socks]
    - service_identity
    - ujson
  host:
    - pip
    - python
    - certifi
    - colorama
    - cryptography
    - dateparser
    - pyopenssl
    - PySocks
    - regex
    - requests
    - requests  # [socks]
    - service_identity
    - ujson
  run:
    - python
    - certifi
    - colorama
    - cryptography
    - dateparser
    - pyopenssl
    - PySocks
    - regex
    - requests
    - requests  # [socks]
    - service_identity
    - ujson

test:
  imports:
    - unicorn_binance_rest_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-rest-api.html
  summary: An unofficial Python API to use the Binance REST API`s.
  description: |
    An unofficial Python API to use the Binance REST API`s (com+testnet, com-margin+testnet, com-isolated_margin+testnet, 
    com-futures+testnet, us, tr) in a easy, fast, flexible, robust and fully-featured way.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api
  doc_url: https://unicorn-binance-rest-api.docs.lucit.tech

extra:
  recipe-maintainers:
    - oliver-zehentleitner
